logging:
  level:
    net.shyshkin: debug

app.reader:
  txt.encoding: UTF-8
app.sql.encoding: UTF-8
app.web-service:
  base-url: http://ddos.shyshkin.org:8080
  cities-endpoint: /cities/all
  accept-type: text/event-stream

spring:
  main:
    web-application-type: none
  batch:
    jdbc:
      platform: mysql
      initialize-schema: always
  datasource:
    jdbc-url: jdbc:mysql://localhost:23306/batch_db
    username: batch_user
    password: batch_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  population-datasource:
    jdbc-url: jdbc:mysql://localhost:33306/population_db
    username: population_user
    password: population_password
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: external_db
  population-datasource:
    jdbc-url: jdbc:mysql://ddos.shyshkin.org:33306/population_db
    username: population_user
    password: population_password
    driver-class-name: com.mysql.cj.jdbc.Driver
